### ISSUE TITLE
cataclysm-dda-9999-r9 breaks on install phase

### ISSUE THREAD

**Issue by theodis** [leycec/raiagent#100]
The merged pull request https://github.com/CleverRaven/Cataclysm-DDA/pull/49108

Has broken the cataclysm-dda-9999-r9 ebuild

During the install phase the sandbox is broken attempting to do the following line
install -Dm755 -t /usr/share/applications/ data/xdg/org.cataclysmdda.CataclysmDDA.desktop

The Makefile constructs the path with the following lines
SHARE_DIR=$(DESTDIR)$(PREFIX)/share
install -Dm755 -t $(SHARE_DIR)/applications/ data/xdg/org.cataclysmdda.CataclysmDDA.desktop

I corrected this locally by adding 
DESTDIR="${ED}"
to
`    CATACLYSM_EMAKE_NCURSES=(
        # Unlike all other paths defined below, ${PREFIX} is compiled into
        # installed binaries and therefore *MUST* refer to a runtime rather
        # than installation-time directory (i.e., relative to ${ESYSROOT}
        # rather than ${ED}).
        PREFIX="${ESYSROOT}"/usr

        # Install-time directories. Since ${PREFIX} does *NOT* refer to an
        # install-time directory, all variables defined by the makefile
        # relative to ${PREFIX} *MUST* be redefined here relative to ${ED}.
        DESTDIR="${ED}"
        BIN_PREFIX="${ED}"/usr/bin
        DATA_PREFIX="${ED}"/usr/share/${PN}
        LOCALE_DIR="${ED}"/usr/share/locale

        # Unconditionally enable backtrace support. Note that:
        # * Enabling this functionality incurs no performance penalty.
        # * Disabling this functionality has undesirable side effects,
        #   including:
        #   * Stripping of symbols, which Portage already does when requested.
        #   * Disabling of crash reports on fatal errors, a tragically common
        #     occurence when installing the live version.
        # Ergo, this support should *NEVER* be disabled.
        BACKTRACE=1

        # Unconditionally add debug symbols to executable binaries, which
        # Portage then subsequently strips by default.
        DEBUG_SYMBOLS=1

        # Link against Portage-provided shared libraries.
        DYNAMIC_LINKING=1

        # Enable tests if requested.
        RUNTESTS=$(usex test 1 0)

        # Enable code style and JSON linting if requested.
        ASTYLE=$(usex astyle 1 0)
        LINTJSON=$(usex lintjson 1 0)

        # Since Gentoo's ${L10N} USE_EXPAND flag conflicts with this makefile's
        # flag of the same name, temporarily prevent the former from being
        # passed to this makefile by overriding the current user-defined value
        # of ${L10N} with the empty string. Failing to do so results in the
        # following link-time fatal error:
        #     make: *** No rule to make target 'en', needed by 'all'.  Stop.
        L10N=
    )
`

**Comment by leycec** [comment]
**Fantastic!** Thanks a zombie-load for the detailed writeup *and* trivial fix, Stickman Theodis. It would've taken me ages to find that fix, too. I'll get this patched up for everyone straight away.

**Comment by leycec** [comment]
**OMFG.** I *cannot* believe they've allowed C:DDA's GitHub repository to bloat so extremely. The `master` branch alone is now pushing 3.0GB! On our antiquated copper ADSL2+ line openly rusting in the Canadian wilderness, this means I can't even reasonably test my own live ebuild anymore. :vomiting_face:
