### ISSUE TITLE
Ebuild Parsing errors - EAPI 5

### ISSUE THREAD

**Issue by scottfurry** [leycec/raiagent#103]
Gentoo tree update (3Q/2022) resulted in changes to ebuild standards. Several ebuilds in raigent tree produced error messages because of Gentoo changes.

Typical error message:
```
     Reading category  52|176 ( 29): dev-perl... 
 * ERROR: dev-perl/Text-MicroTemplate-0.24::raiagent failed (depend phase):
 *   perl-module: EAPI 5 not supported
 * 
 * Call stack:
 *                        ebuild.sh, line 618:  Called source '/var/db/repos/raiagent/dev-perl/Text-MicroTemplate/Text-MicroTemplate-0.24.ebuild'
 *   Text-MicroTemplate-0.24.ebuild, line  11:  Called inherit 'perl-module'
 *                        ebuild.sh, line 298:  Called __qa_source '/var/db/repos/gentoo/eclass/perl-module.eclass'
 *                        ebuild.sh, line 114:  Called source '/var/db/repos/gentoo/eclass/perl-module.eclass'
 *               perl-module.eclass, line  32:  Called die
 * The specific snippet of code:
 *   		die "${ECLASS}: EAPI ${EAPI:-0} not supported"
 * 
 * If you need support, post the output of `emerge --info '=dev-perl/Text-MicroTemplate-0.24::raiagent'`,
 * the complete build log and the output of `emerge -pqv '=dev-perl/Text-MicroTemplate-0.24::raiagent'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/Text-MicroTemplate-0.24'
```

Ebuilds that are affected and producing the error message above:

- dev-perl/Compiler-Lexer
- dev-perl/Config-Identity
- dev-perl/Data-Record
- dev-perl/Data-Section-Simple
- dev-perl/ExtUtils-MakeMaker-CPANfile
- dev-perl/Minilla
- dev-perl/Module-CPANfile
- dev-perl/MooX-Options
- dev-perl/PAUSE-Permissions
- dev-perl/PAUSE-Permissions-MetaCPAN
- dev-perl/Parse-LocalDistribution
- dev-perl/Parse-PMFile
- dev-perl/Perl-MinimumVersion-Fast
- dev-perl/Spellunker
- dev-perl/TOML
- dev-perl/TOML-Parser
- dev-perl/Test-Deep-Fuzzy
- dev-perl/Test-Directory
- dev-perl/Test-MinimumVersion-Fast
- dev-perl/Test-PAUSE-Permissions
- dev-perl/Text-MicroTemplate

**Comment by leycec** [comment]
**OMG.** I hang my bald head in public shame. I'd entirely forgotten that we'd even packaged Perl cruft. Since none of that intersects anymore with my current interests, I've last-rited (i.e., permanently removed) the entire `dev-perl/*` subtree.

Thanks so much for the lucid details, @scottfurry. You're stunning! I hope you're having an equally great summer wherever you may roam in Canada. You rock. :rock:

**Comment by scottfurry** [comment]
To our beloved friend dev-perl...
In nómine Patris, et Fílii, et Spíritus Sancti. Amen
