### ISSUE TITLE
Cataclysm: DDA 0.G?

### ISSUE THREAD

**Issue by Anrock** [leycec/raiagent#107]
Hi, 0.G was released recently. 

I've renamed -9999 ebuild to -0.9g and it seems to build successfuly but the game reports 0.f version though I swear I saw `ebuild ... manifest` downloading `0.G.zip`.

**Comment by leycec** [comment]
**Wonderful!** Thanks so much for the heads up, @Anrock. I'll just go ahead and bump that for everyone tonight. The zombie apocalypse must be confronted with confidence, home-made nail bats, and death mobiles. :zombie:

**Comment by leycec** [comment]
**Resolved by fc11486.** Enjoy the world-shattering apocalypse like never before, @Anton! :smile:
