### ISSUE TITLE
Ebuild parsing error - EAPI value - dev-libs/libsecp256k1

### ISSUE THREAD

**Issue by scottfurry** [leycec/raiagent#108]
It appears gentoo infrastructure was changed. This has cause some serious upheaval in several ebuilds (see gentoo bug #913237 ). Appears change also affects ebuild in this repo:

```
[4] "raiagent" /var/db/repos/raiagent (cache: parse|ebuild*3.0.24#metadata-md5#metadata-flat#assign)
   Reading category  49|178 ( 27): dev-libs... * ERROR: dev-libs/libsecp256k1-0.1_pre20190331::raiagent failed (depend phase):
 *   eutils: EAPI 7 not supported
 * 
 * Call stack:
 *                             ebuild.sh, line 628:  Called source '/var/db/repos/raiagent/dev-libs/libsecp256k1/libsecp256k1-0.1_pre20190331.ebuild'
 *   libsecp256k1-0.1_pre20190331.ebuild, line   6:  Called inherit 'autotools' 'eutils'
 *                             ebuild.sh, line 308:  Called __qa_source '/var/db/repos/gentoo/eclass/eutils.eclass'
 *                             ebuild.sh, line 123:  Called source '/var/db/repos/gentoo/eclass/eutils.eclass'
 *                         eutils.eclass, line  18:  Called die
 * The specific snippet of code:
 *   	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/libsecp256k1-0.1_pre20190331::raiagent'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/libsecp256k1-0.1_pre20190331::raiagent'`.
 * Working directory: '/usr/lib/python3.11/site-packages'
 * S: '/libsecp256k1-0.1_pre20190331'

ebuild failed with status 1
     Reading category  49|178 ( 27): dev-libs...
cannot properly execute /var/db/repos/raiagent/dev-libs/libsecp256k1/libsecp256k1-0.1_pre20190331.ebuild
     Reading category 178|178 (100) Finished           
```

**Comment by leycec** [comment]
`</facepalm>`

Thanks so much for the rapid response time, @scottfurry. I'm breathless before your humbling prowess. And...

Thanks fer nuthin', official Gentoo devs! Like, serious. I both love and abhor them in equal measure. They hate backward compatibility. This much is sadly clear. They giddily break backward compatibility over their collective knees while pretending that modest third-party overlays like us simply don't exist. But we do! Oh, how we do. And we never forget that you hate us, official Gentoo devs. *So. Much. Urgh.*

**Comment by scottfurry** [comment]
Gentoo bug I filed was about a whole pile of dev-r/ ebuilds. You're not alone.

**Comment by leycec** [comment]
**Boom.** Thankfully, Portage itself now officially packages `libsecp256k1`. Let's pretend this never happened.

Oh – and I wouldn't be shocked <sup>*utterly shocked!*</sup> if there wasn't even more breakage elsewhere in the overlay. Please throw me a desperate plea for GitHub resolution if you stumble over any other vicious caltrops in the road to open-source progress.

Until then, you do the phenomenal Gentoo work. Thanks so much for your profound suffering and willingness to help us limp along. I shall pray for eventual sanity from our dev masters in the Portage tree. *Stop breaking worky, Gentoo devs.* :expressionless: :exploding_head: :boom:
