### ISSUE TITLE
[Bug] CDDA link to official install instruction dead

### ISSUE THREAD

**Issue by quintuple-lained** [leycec/raiagent#114]
the link to the cataclysm dark days ahead gentoo install instructions is dead, the domain is for sale

https://cddawiki.chezzo.com/cdda_wiki/index.php?title=How_to_compile#Gentoo

![2024-10-29-102020_hyprshot](https://github.com/user-attachments/assets/e900cb0f-29f7-437a-aabd-c1e5edb086e6)

**Comment by leycec** [comment]
**WOAH.** That's massive badness. Thanks so much for the heads-up, @quintuple-lained. Hey... *wait a minute.* Is "quintuple lained" like four times the *Serial Experiments Lain*!? I support you in this brave endeavour. One cannot have enough Lain. :smile: 

Sadly, given what I've read on Reddit (e.g., [this thread](https://www.reddit.com/r/cataclysmdda/comments/1cktpuz/what_happen_to_the_chezzo_wiki/)), there is currently *no* working C:DDA wiki. Instead, everyone now advises using the [Hitchhiker's Guide to the Cataclysm](https://cdda-guide.nornagon.net). So, that's *probably* what we'll switch the URL to. Probably. `</sigh>`

**Comment by quintuple-lained** [comment]
im glad you enjoy my username, im assuming this issue is to stay open until a new link is found?

**Comment by leycec** [comment]
> im assuming this issue is to stay open until a new link is found?

**Totally.** Actually... is there a Wayback Machine copy of the old link? If so, we could probably just link to that and call it a day. If not, this issue will remain open until the heat death of the universe. :smile_cat:

**Comment by quintuple-lained** [comment]
There [is](https://web.archive.org/web/20220127170234/https://cddawiki.chezzo.com/cdda_wiki/index.php?title=How_to_compile#Gentoo), but considering the recent attack on the archive it may not be a perfect solution

**Comment by leycec** [comment]
**Superbness!** Excellent catch. Thanks so much for being on the ball and then riding that ball like a boss, @quintuple-lained.

I... agree that the recent DDoS attacks on Wayback are concerning. They sadden us all. But "the perfect is the enemy of the good," *blah, blah*. It's a trite and annoying response, but it's also maybe true here. A Wayback URL is definitely good enough for this overlay. I have no standards and am lazy. Is a Wayback URL good enough for Portage? Maybe... not. I'm happy to let that be somebody else's problem, though. Let them eat cake and buggy URLs.

If you'd like to submit a PR for this, I'd :heart_eyes_cat: to merge that. Alternately, I'll do this myself at some point after you poke me in the ribs a few times about this. `</my_ribs_hurt_already>`

**Comment by quintuple-lained** [comment]
@leycec made the pull request

**Comment by leycec** [comment]
*Aaaaaaaaaand...* merged! Thanks for being so awesome, @quintuple-lained. May all your anime be triply blessed.
