### ISSUE TITLE
app-misc/powerline-1.3.1

### ISSUE THREAD

**Issue by un-amigo** [leycec/raiagent#24]
ERROR: app-misc/powerline-1.3.1::raiagent failed (install phase):
 *   You are not specifying README.gentoo contents!

https://bpaste.net/show/9547d585d17f
https://bpaste.net/show/fce282348544

**Comment by leycec** [comment]
**Fixed.** Thanks for the detailed bug report, [un-amigo](https://github.com/un-amigo). You're awesome!
