### ISSUE TITLE
Cataclysm DDA dont work with "Catasounds" pack

### ISSUE THREAD

**Issue by aaferrari** [leycec/raiagent#41]
Thanks to this overlay few days ago I was able to install this game and since then I liking it a lot. It turns out that doing a little research I found a [package of sounds](http://chezzo.com/cdda/catasounds.zip) that can be used with Cataclysm ([some](https://www.youtube.com/watch?v=Bfe9KnuCyUk) [videos](https://www.youtube.com/watch?v=YMc_5LolPhI) [as](https://www.youtube.com/watch?v=lm6IRweDZA8) [demonstration](https://www.youtube.com/watch?v=dq_H2BlsE9A)) but at start a game, I get the following:
<pre>DEBUG: Error loading data from json: 
/usr/share/games/cataclysm-dda/json//soundset.json: line 2:5: unrecognized JSON 
object, type: "sound_effect"
  Press spacebar...</pre>
After I get messages of this type again and again
<pre>DEBUG: Can't find t_dirtmound 
  Press spacebar...</pre>
Thus it become unplayable. [According to the forum](http://smf.cataclysmdda.com/index.php?topic=10390.msg246793#msg246793), just enough with unpack everything in the data folder of the program (/usr/share/games/cataclysm-dda/) but does not work in my case.
I do not know whether to make any further process for that this package work with the version of Linux but if it helps anything, these are the USE flags that I have enabled:
<pre> * Found these USE flags for games-roguelike/cataclysm-dda-0.9c-r2:
 U I
 - - clang   : Build with clang++ rather than g++ (experimental!)
 - - lua     : Enable Lua scripting support (e.g., for modding)
 + + ncurses : Install ncurses-based terminal executable (recommended)
 + + nls     : Add Native Language Support (using gettext - GNU locale utilities)
 + + sdl     : Install SDL-based X11 executable (recommended)
 + + sound   : Enable SDL-based sound support</pre>

**Comment by leycec** [comment]
> Thanks to this overlay few days ago I was able to install this game and since then I liking it a lot.

Thank _you_ for the super-detailed bug report. And... I'm totally sorry it failed for you. This is unacceptable, so I'll see what I can cobble together over the next few days.

Superficially, I note that there exists a [Catasounds GitHub repository](https://github.com/vulkans22/CataSounds). The thing to do will probably be to:

* Add a new `games-roguelike/cataclysm-dda-catasounds` ebuild tracking that repository.
* Add a new `catasounds` USE flag that, when enabled, pulls in that ebuild as a runtime dependency _and_ properly integrates that dependency with the currently installed version of C:DDA.

**Comment by leycec** [comment]
**The plot thickens.** According to [this forum post](http://smf.cataclysmdda.com/index.php?topic=10390.105):

> 1) Download and unpack latest **experimental build** from here: http://dev.narc.ro/cataclysm/jenkins-latest/Windows/Tiles/

From your excellent bug report, I gather you're currently running the latest **stable build** (0.9.c). If the above installation instructions are accurate, you probably need to run the **unstable build** (9999) instead. To do so, you'll need to:

1. Hard-unmask `cataclysm-dda-9999` by adding the following line to `/etc/portage/package.accept_keywords`:
        >=games-roguelike/cataclysm-dda-0.9a **
2. Reinstall `cataclysm-dda`:
        emerge cataclysm-dda
3. Manually reinstall Catasounds.

Would you mind giving that a shot, first?

**Comment by leycec** [comment]
With half-hearted apologies, I'm inclined to close this issue – which doesn't appear to be an ebuild issue.

Thanks for all the detailed fish, aaferrari. :fishing_pole_and_fish:
