### ISSUE TITLE
Cataclysm DDA: USE_XDG_DIR doesn't work

### ISSUE THREAD

**Issue by lucianposton** [leycec/raiagent#43]
cataclysm-dda-0.9c-r2.ebuild defines USE_XDG_DIR; however, this option was not made available until post-0.9c. A future release (and the 9999 live build) will have this option. The fallback behavior is to use the current working dir, which is annoying. https://github.com/CleverRaven/Cataclysm-DDA/blob/2f891d5f34c84ea4f5f278d7b4bd114144e3524d/src/main.cpp#L56

USE_HOME_DIR is available in 0.9c, but simply switching to USE_HOME_DIR would cause some users problems with their save files, I expect. Since the 9999 ebuild already has USE_XDG_DIR set, the best option is probably to just patch 0.9c-r2 to use USE_XDG_DIR, rather than switching to USE_HOME_DIR. I'll try it out, and if it works, I'll send a pull request.

**Comment by leycec** [comment]
**Ugh.**

I must never have tested my `USE_XDG_DIR` "usability improvements" on 0.9c, much to my enduring shame. I'm terribly sorry about that. Lax testing will be death of us all. :scream: 

I agree with your detailed synopsis. The fallback behaviour of using the current directory is sufficiently bad as to be broken, so let's _not_ do that. Thankfully, you've saved us all by diligently providing a working pull request.

You are mana from code heaven!
