### ISSUE TITLE
Cataclysm build broken: new Makefile variable clashes with portage variable

### ISSUE THREAD

**Issue by lucianposton** [leycec/raiagent#46]
https://github.com/CleverRaven/Cataclysm-DDA/commit/376bb9a9e4a313b609a8c218b694f68ada883a23#diff-b67911656ef5d18c4ae36cb6741b7965 added BUILD_PREFIX to change the build dir. This just so happens to be an env variable used by portage ("/var/tmp/portage" by default). This causes some artifacts to appear in /var/tmp/, e.g. /var/tmp/portageobj for the obj dir.

The safest bet is probably to sed the cataclysm makefile to replace the variable name e.g. s/BUILD_PREFIX/CATACLYSM_BUILD_PREFIX/.

**Comment by leycec** [comment]
**Urgh.** Thanks for the observant catch – and even more observant suggestion, which I'm in full agreement with. `sed` hackage for the win!

In theory, I'll get this patched up sometime over the course of the next several days. :sunrise:

**Comment by leycec** [comment]
**This should be fixed now.** For maintenance, the C:DDA ebuild has also been improved to:

* Avoid inheriting the now-deprecated `games` eclass.
* Provide a `test` USE flag for running C:DDA tests.

Thanks again, [Lucian](https://github.com/lucianposton). (_Nice avatar, too._)
