### ISSUE TITLE
games-roguelike/cataclysm-dda: epatch not available

### ISSUE THREAD

**Issue by atlaua** [leycec/raiagent#52]
The -9999 ebuild uses epatch without inheriting eutils. You should either add `inherit eutils` to the top of the ebuild or bump the ebuild to `EAPI=6` and replace `epatch` by `eapply`.

For reference, here's a useful guide to EAPI 6: https://blogs.gentoo.org/mgorny/2015/11/13/the-ultimate-guide-to-eapi-6/

**Comment by leycec** [comment]
**Fixed by 31a0d0c4b.** I've previously migrated a few other malingering ebuilds over to EAPI 6. So, doing so here as well seemed like the least awful solution. See #49 for further commentary, gratitude, and adulation.
