### ISSUE TITLE
(qa) games-roguelike/cataclysm-dda

### ISSUE THREAD

**Issue by l29ah** [leycec/raiagent#54]
/var/tmp/paludis/games-roguelike-cataclysm-dda-9999-r6/temp/loadsaveenv: line 4129: games_pkg_postinst: command not found

**Comment by leycec** [comment]
> `/var/tmp/paludis`

We meet again, Paludis.

> games_pkg_postinst: command not found

This is shameful. Consequently, I feel bad. <sup>_Thanks alot._</sup>

We recently migrated away from the now deprecated `games` eclass, but clearly neglected to complete the migration. `emerge` presumably ignores that attempt to call an undefined function, whereas Paludis presumably fails on doing so. We use the former and thus never hit this. _Urgh!_

This has now been resolved by 4f29e21852dd. Thanks for the report – and sorry for the breakage. :bowtie:

**Comment by l29ah** [comment]
Nah, it's not errexit, but just a warning.
