### ISSUE TITLE
games-roguelike/cataclysm-dda-0.9c-r4 fails compilation 

### ISSUE THREAD

**Issue by mothringer** [leycec/raiagent#59]
The above referenced ebuild fails compilation for me with the error below.

src/crafting.cpp: In member function ‘void player::complete_disassemble()’:
src/crafting.cpp:2045:47: error: ‘pow’ is not a member of ‘std’
     float component_success_chance = std::min(std::pow(0.8f, dis_item.damage), 1.0);
                                               ^
src/crafting.cpp:2045:47: note: suggested alternative:
In file included from /usr/include/features.h:368:0,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/os_defines.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/c++config.h:482,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/string:38,
                 from src/crafting.cpp:1:
/usr/include/bits/mathcalls.h:153:1: note:   ‘pow’
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
 ^
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/posix_time.cpp -o obj/posix_time.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/skill.cpp -o obj/skill.o
make: *** [Makefile:448: obj/crafting.o] Error 1
make: *** Waiting for unfinished jobs....
src/player.cpp: In member function ‘void player::pick_style()’:
src/player.cpp:9791:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ma_style_callback> ma_style_info(new ma_style_callback());
          ^
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/memory:81:0,
                 from src/messages.h:6,
                 from src/effect.h:6,
                 from src/creature.h:9,
                 from src/character.h:4,
                 from src/player.h:4,
                 from src/player.cpp:1:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;

**Comment by leycec** [comment]
**Ugh.** Thanks for the detailed report, [mothringer](https://github.com/mothringer). Incidentally, excellent username as well. Because we could all use a little more [Mothra](https://www.youtube.com/watch?v=76ubfmtd8xM).

Sadly, this appears to be an upstream issue. The fix is trivial: the upstream `src/crafting.cpp` file needs to be prepended with the include pragma `#include <cmath>`, at which point compilation should succeed. <sup>_Completely untested. May destroy your life._</sup>

Would you mind filing an upstream issue at the [C:DDA issue tracker](https://github.com/CleverRaven/Cataclysm-DDA/issues), ideally including the same error output *and* the proposed solution? If not, that's cool. Time's a bit *scarce* on my end, however.

So it goes. ⌛️

**Comment by mothringer** [comment]
` * Package:    games-roguelike/cataclysm-dda-0.9c-r4
 * Repository: raiagent
 * Maintainer: leycec@gmail.com
 * Upstream:   http://smf.cataclysmdda.com/index.php?board=4.0
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux lua ncurses nls sdl userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
>>> Unpacking cataclysm-dda-0.9c.tar.gz to /var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work
>>> Source unpacked in /var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work
>>> Preparing source in /var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work/Cataclysm-DDA-0.C ...
 * Applying cataclysm-dda-0.9c-USE_XDG_DIR.patch ...
 [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work/Cataclysm-DDA-0.C ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work/Cataclysm-DDA-0.C ...
 * Compiling ncurses interface...
make -j9 PREFIX=/usr BIN_PREFIX=/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/image//usr/bin DATA_PREFIX=/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/image///usr/share/cataclysm-dda LOCALE_DIR=/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/image//usr/share/locale DYNAMIC_LINKING=1 L10N= RELEASE=1 NATIVE=linux64 LUA=1 LOCALIZE=1 USE_HOME_DIR=1 USE_XDG_DIR=0 
#define VERSION "0.C"
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/mapgenformat.cpp -o obj/mapgenformat.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/overmapbuffer.cpp -o obj/overmapbuffer.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/veh_typedef.cpp -o obj/veh_typedef.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/iexamine.cpp -o obj/iexamine.o
cd src/lua && lua generate_bindings.lua
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/iuse_software_snake.cpp -o obj/iuse_software_snake.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/savegame_json.cpp -o obj/savegame_json.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/monattack.cpp -o obj/monattack.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/editmap.cpp -o obj/editmap.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/sounds.cpp -o obj/sounds.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/bionics.cpp -o obj/bionics.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/crafting.cpp -o obj/crafting.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/active_item_cache.cpp -o obj/active_item_cache.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/player.cpp -o obj/player.o
[01m[Ksrc/crafting.cpp:[m[K In member function ‘[01m[Kvoid player::complete_disassemble()[m[K’:
[01m[Ksrc/crafting.cpp:2045:47:[m[K [01;31m[Kerror: [m[K‘[01m[Kpow[m[K’ is not a member of ‘[01m[Kstd[m[K’
     float component_success_chance = std::min(std::pow(0.8f, dis_item.damage), 1.0);
[01;32m[K                                               ^[m[K
[01m[Ksrc/crafting.cpp:2045:47:[m[K [01;36m[Knote: [m[Ksuggested alternative:
In file included from [01m[K/usr/include/features.h:368:0[m[K,
                 from [01m[K/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/os_defines.h:39[m[K,
                 from [01m[K/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/x86_64-pc-linux-gnu/bits/c++config.h:482[m[K,
                 from [01m[K/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/string:38[m[K,
                 from [01m[Ksrc/crafting.cpp:1[m[K:
[01m[K/usr/include/bits/mathcalls.h:153:1:[m[K [01;36m[Knote: [m[K  ‘[01m[Kpow[m[K’
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
[01;32m[K ^[m[K
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/posix_time.cpp -o obj/posix_time.o
g++ -DRELEASE -DLOCALIZE -DPREFIX="/usr" -DUSE_HOME_DIR -O3 -pipe -march=native  -Wall -Wextra    --std=c++11 -MMD -m64    -DLUA -D_GNU_SOURCE -I/usr/include/ncursesw -c src/skill.cpp -o obj/skill.o
make: *** [Makefile:448: obj/crafting.o] Error 1
make: *** Waiting for unfinished jobs....
[01m[Ksrc/player.cpp:[m[K In member function ‘[01m[Kvoid player::pick_style()[m[K’:
[01m[Ksrc/player.cpp:9791:10:[m[K [01;35m[Kwarning: [m[K‘[01m[Ktemplate<class> class std::auto_ptr[m[K’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<ma_style_callback> ma_style_info(new ma_style_callback());
[01;32m[K          ^[m[K
In file included from [01m[K/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/memory:81:0[m[K,
                 from [01m[Ksrc/messages.h:6[m[K,
                 from [01m[Ksrc/effect.h:6[m[K,
                 from [01m[Ksrc/creature.h:9[m[K,
                 from [01m[Ksrc/character.h:4[m[K,
                 from [01m[Ksrc/player.h:4[m[K,
                 from [01m[Ksrc/player.cpp:1[m[K:
[01m[K/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/unique_ptr.h:49:28:[m[K [01;36m[Knote: [m[Kdeclared here
   template<typename> class auto_ptr;
[01;32m[K                            ^[m[K
 * ERROR: games-roguelike/cataclysm-dda-0.9c-r4::raiagent failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=games-roguelike/cataclysm-dda-0.9c-r4::raiagent'`,
 * the complete build log and the output of `emerge -pqv '=games-roguelike/cataclysm-dda-0.9c-r4::raiagent'`.
 * The complete build log is located at '/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/temp/environment'.
 * Working directory: '/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work/Cataclysm-DDA-0.C'
 * S: '/var/tmp/portage/games-roguelike/cataclysm-dda-0.9c-r4/work/Cataclysm-DDA-0.C'
`

**Comment by mothringer** [comment]
I opened an issue on the upstream tracker.

**Comment by leycec** [comment]
**Cheers.** Under the safe assumption that this is an upstream issue, this is (*hopefully*) closable on our end. Feel free to reopen this if upstream says otherwise.

Thanks again for flying the post-apocalyptic airways with `raiagent`.
