### ISSUE TITLE
QA issues with the repository

### ISSUE THREAD

**Issue by mgorny** [leycec/raiagent#60]
There's [Gentoo bug #613494](https://bugs.gentoo.org/show_bug.cgi?id=613494) open for QA & contact issues with the repository. Please fix the issues urgently or at least respond on the bug, and provide a proper contact address on the bug. Otherwise, the repository will be removed.

**Comment by leycec** [comment]
Awesome! Thanks for the heads up, Michał. I'll attend to it promptly. Which is to say **now.**

**Comment by leycec** [comment]
**Fixed by 17c506ec6b53d,** removing the offending `media-video/devede` package. Thanks again!
