### ISSUE TITLE
net-vpn/zeronet: systemd can not start service

### ISSUE THREAD

**Issue by radjah** [leycec/raiagent#63]
Error:
```
zeronet.service: Main process exited, code=exited, status=203/EXEC
zeronet.service: Unit entered failed state.
zeronet.service: Failed with result 'exit-code'.
```
Fix:
replace "`##!/usr/bin/env`" with "`#!/usr/bin/env`" in `/usr/bin/zeronet`

Line in ebuild
https://github.com/leycec/raiagent/blob/35c071caa551268c26ca3a1e1454fb4368fb82bd/net-vpn/zeronet/zeronet-9999.ebuild#L159

**Comment by leycec** [comment]
_Excellent._ I maintain a Poettering-free system and wasn't able to actively test this. Which is bad, and absolutely my fault.

Thanks for doing all of the hard work for me! I humbly appreciate that. I'll patch the failing shebang line shortly.

**Comment by leycec** [comment]
**Done.** If you notice any other lingering badness, just let me know. ZeroNet is a high priority for me. So, this absolutely matters. And thanks again! Your detailed report helped a bunch.
