### ISSUE TITLE
[Feature Request] app-misc/powerline add support for i3 bar

### ISSUE THREAD

**Issue by liketechnik** [leycec/raiagent#67]
Powerline has support for i3bar as stated in their [docs](https://powerline.readthedocs.io/en/latest/usage/wm-widgets.html#i3-bar), but I can't find the script referenced there. Am I just not searching in the right place or is this script stripped during the install phase (what I think is happening, because there is no useflag for i3/i3bar)? I'd really like to use the powerline bar for i3.

**Comment by leycec** [comment]
That's... a very astute question. I've recently contemplated migrating from a [custom FVWM theme I've run for the past *decade*](https://github.com/leycec/fluviol) to i3. So, this is painfully relevant to me.

Your assumption is almost certainly correct, although I haven't examined this *exact* issue in detail yet. We'll definitely need to add a new `i3` USE flag and corresponding logic in the `python_install_all` phase to conditionally install all i3-specific assets, resources, and scripts when that flag is enabled.

I'll try *really,* *really* hard to attend to this in the next several days. Apologies for the month-long delay, too. My [father-in-law recently passed away](http://yourlifemoments.ca/sitepages/obituary.asp?oId=1095573). It has certainly been a challenging autumn.

This Canadian maple leaf is for you, @liketechnik. Thanks again! :maple_leaf:

**Comment by leycec** [comment]
**Boom.** In theory, enabling the `i3bar` USE flag should now install i3-specific support files. To integrate these files with your existing i3 configuration, append the following to `~/.config/i3/config` after replacing `${POWERLINE_FONT_NAME}` and `${POWERLINE_FONT_SIZE}` with the pango-compatible name and size in pt (*points*) of a Powerline-patched font installed by the `media-fonts/powerline-fonts` package (e.g., `font pango:Source Code Pro for Powerline 11` after running `USE='sourcecodepro' emerge powerline-fonts`):

```
 	bar {
 		status_command python /usr/share/powerline//i3/powerline-i3.py
 		font pango:${POWERLINE_FONT_NAME} ${POWERLINE_FONT_SIZE}
 	}
```

Relatedly, I've also added Powerline support for [lemonbar](https://github.com/LemonBoy/bar). Merry Christmas! *Ho, ho, ho.*

**Comment by liketechnik** [comment]
Thank you very much for including this so fast. Testing it out just in this very moment :)
Merry Christmas!
P.S.: Sorry to hear about the passing of your relative, wish you all the best.

**Comment by liketechnik** [comment]
Ok, looks like the i3 plugin needs the i3ipc python library (https://github.com/acrisci/i3ipc-python). The problem is, that this isn't currenlty packages as a gentoo ebuild. But after succesfully installing it locally via the setup.py script, everything's working fine.
