### ISSUE TITLE
games-roguelike/cataclysm-dda-9999-r9: no debugging symbols

### ISSUE THREAD

**Issue by l29ah** [leycec/raiagent#72]
As seen by `gdb /usr/bin/cataclysm`:
```
Reading symbols from /usr/bin/cataclysm...
Reading symbols from /usr/lib/debug//usr/bin/cataclysm.debug...
(No debugging symbols found in /usr/lib/debug//usr/bin/cataclysm.debug)
```

`DEBUG_SYMBOLS=1` should be turned on unconditionally, like in every other Gentoo ebuild, since symbol stripping is done at the later stage and in `emerge` is governed by `FEATURES`. To make things worse, `RELEASE=0` in cataclysm-dda makes the game really slow.

**Comment by leycec** [comment]
**Excellent catches!** I confess that I only test the `debug` USE flag for installability and superficial usability; I've never actually attempted a full run-through with debugging enabled. In hindsight, that might have been a good idea.

> `DEBUG_SYMBOLS=1` should be turned on unconditionally...

You're quite right, of course. It shall be so.

> `RELEASE=0` in cataclysm-dda makes the game really slow.

That's working exactly as intended then. Disabling release optimizations enables a debug build. Either you want that (and everything that entails, including computationally expensive checks, tests, and other developer-specific validation logic) or you don't.

It sounds like you don't. `</shrug>`

**Comment by leycec** [comment]
Thanks again for the voluminous assistance, @l29ah! Commit 30bf6e1 resolves the `DEBUG_SYMBOLS=1` portion of this issue – *exactly* as suggested. As for the remainder, well... `RELEASE=0` slowdown is arguably more of an upstream issue.

If you've got any other specific quandaries, please re-open this issue *or* submit a new issue. I'd be delighted to perfect these e-builds with your generous help. Until then, tasty vegan hamburgers for all! :hamburger:
