### ISSUE TITLE
missing shiboken2.pc file

### ISSUE THREAD

**Issue by soltysek** [leycec/raiagent#73]
Hi,

I'm trying to build QT application that requires pyside2 and shiboken2.
So I've installed dev-python/shiboken2 and dev-python/pyside2 and I'm getting configure error:

> Project ERROR: ERROR: Shiboken2, which is required to build the Python Bindings, could not be found. Make sure it is available to pkg-config.

When I change te source file to look for shiboken2-python3.7 this check passes, but I'm getting error about PySide2: 

> Project ERROR: ERROR: PySide2, which is required to build the Python Bindings, could not be found. Make sure it is available to pkg-config.

Doing the same trick for PySide2 does not work as pyside2*.pc files have `Requires: shiboken2` which does not exist.

.pc files installed by both packages:

> $ ls /usr/lib64/pkgconfig/ | grep shiboken
> shiboken2-python2.7.pc
> shiboken2-python3.7.pc
> shiboken2-python3.8.pc

> $ ls /usr/lib64/pkgconfig/ | grep pyside
> pyside2.pc
> pyside2-python2.7.pc
> pyside2-python3.7.pc
> pyside2-python3.8.pc

Solution: 
dev-python/shiboken2 should install also shiboken2.pc file

Preferred solution: 
pyside2-python*.pc files should have set Requires field for proper shiboken2-python*

**Comment by leycec** [comment]
**Yikes!** Thanks a bunch for this detailed issue report *and* that succinct pair of trailing solutions. You're absolutely right about both, of course:

* The lack of a `/usr/lib64/pkgconfig/shiboken2.pc` file is a shameful regression. (*Woopsie.*)
* The ambiguous `Requires: shiboken2` fields in `/usr/lib64/pkgconfig/pyside2*.pc` files is a brand new issue. I'm grateful you caught this for me, but also ashamed I never noticed that.

PySide2 on Gentoo is a first-class concern for me, so I'll get this patched up pronto. :+1:

**Comment by soltysek** [comment]
No problem, I'm used to writing detailed bug/issue reports ;) When you have **cost efficient** IT support at work then you either learn this or have to explain over an over again the same things to some guy from India ;)

**Comment by leycec** [comment]
**Bam!** The shiboken2 and PySide2 ebuilds have been bumped up to `shiboken2-5.12.5-r1` and `pyside2-5.12.5-r1`. If you could manually test both on your end and verify that they resolve your project's issues and bring balance back to the Qt Force, I *will* cry man tears of salty joy. :joy:
