### ISSUE TITLE
pyside and shiboken version bump

### ISSUE THREAD

**Issue by soltysek** [leycec/raiagent#76]
Hi,

Please add ebuilds for shiboken  / pyside verion 5.14 as current version is failing to build against qt 5.14.0 (or I just have bad luck / something wrong on my two systems) ;)

**Comment by leycec** [comment]
You got it! The holidays are always a bumpy ride, but I'm back in action and all out of bubblegum.

I'm astonished, *simply astonished,* that PySide2 5.12.5 is forwards-incompatible with newer versions of Qt. O.K.; so, I'm not astonished at all. PySide2 is a fragile beast at best. This definitely isn't your fault or the fault of your particular setup. It's PySide2's fault all the way down. `</sigh>`

I'll devote the next several days to bumping PySide2 & Friends to **5.14.0.** There's probably little point in supporting 5.13.2 at this belated point, sadly. Thanks for the friendly reminder, @soltysek. You rock, as always. :guitar:

**Comment by leycec** [comment]
**Bumped by 27072fe.** Houston, we have bump!

Fire away another issue if you have any... *issues.* Until then, thanks again for the useful heads-up. :upside_down_face:
