### ISSUE TITLE
dev-python/pyside2-5.15.1:  'stddef.h' file not found

### ISSUE THREAD

**Issue by baybal** [leycec/raiagent#98]
Build fails with  `'stddef.h' file not found` again

Build log https://gist.github.com/baybal/2ae6f28f3675f26f52b517ff160a5415
Env https://gist.github.com/baybal/d94e0c16bf799b82bb4cddb7f7eb81d2

**Comment by baybal** [comment]
GCC 10.3.0
Clang 11.1.0

**Comment by leycec** [comment]
Thanks for the detailed build log, @baybal! Sadly... I no longer maintain PySide2 here at `::raiagent`. PySide2 is now maintained in Portage itself by official Gentoo developers. *Hallelujah!*

Would you mind redirecting your bug report to the [official Gentoo bug tracker](https://bugs.gentoo.org)? They'll be able to sort you out directly, I'm sure.

Oh, and [I fixed a similar PySide2 issue here a little over a year ago](https://github.com/leycec/raiagent/issues/83). If these two issues are related, <sup>*...they're totally related*</sup> you might be able to solve this on your end by **downgrading LLVM and Clang.**

Of course, that's horrible. You might just want to report this to Gentoo's Bugzilla instead. :wink:
