### ISSUE TITLE
media-libs/libsdl-1.2.9999 causing emerge failure - EAPI

### ISSUE THREAD

**Issue by scottfurry** [leycec/raiagent#99]
Recent emerge resulted in following error message being displayed during calculation of dependencies:
```
 * ERROR: media-libs/libsdl-1.2.9999::raiagent failed (depend phase):
 *   mercurial: EAPI 5 not supported
 * 
 * Call stack:
 *                ebuild.sh, line 645:  Called source '/var/db/repos/raiagent/media-libs/libsdl/libsdl-1.2.9999.ebuild'
 *   libsdl-1.2.9999.ebuild, line  10:  Called inherit 'autotools' 'flag-o-matic' 'mercurial' 'multilib' 'toolchain-funcs' 'eutils'
 *                ebuild.sh, line 329:  Called __qa_source '/var/db/repos/gentoo/eclass/mercurial.eclass'
 *                ebuild.sh, line 114:  Called source '/var/db/repos/gentoo/eclass/mercurial.eclass'
 *         mercurial.eclass, line  20:  Called die
 * The specific snippet of code:
 *   	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
 * 
 * If you need support, post the output of `emerge --info '=media-libs/libsdl-1.2.9999::raiagent'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/libsdl-1.2.9999::raiagent'`.
 * Working directory: '/usr/lib/python3.9/site-packages'
 * S: '/var/tmp/portage/media-libs/libsdl-1.2.9999/work/libsdl-1.2.9999'
```

Appears emerge is complaining about an ebuild with EAPI = 5.
Message is persistent.
System: x86_64 5.10.27
Python 3.9.5
Portage: 3.0.20-r6

**Comment by leycec** [comment]
Thanks for the detailed writeup, dogfighting veteran Scott Furry! Our continued packaging of obsoleted, useless, and frankly risky live ebuilds for libSDL and SDL-sound has been an ongoing source of public shame.

I'll quickly remove both. Then we can pretend none of this ever happened.

**Comment by scottfurry** [comment]
![snoopy-salute](https://user-images.githubusercontent.com/6686571/122866586-71970b00-d2e5-11eb-9697-7233f97bb54b.jpg)

**Comment by Kusoneko** [comment]
I was about to add the same issue here. Seems I was beaten to the punch. c:

**Comment by leycec** [comment]
Our public shame ends here! <sup>...sorry guys</sup>
